version: "3.7"
services:
  m-explore-ros2-humble:
    build:
      context: ../
      dockerfile: .devcontainer/Dockerfile
    working_dir: /workspace/ros_ws
    user: dev

    ports:
      - "80:80"

    init: true
    privileged: true

    environment:
      - DISPLAY=host.docker.internal:0
      - QT_X11_NO_MITSHM=1
      - LIBGL_ALWAYS_INDIRECT=0
    volumes:
      # Update this to wherever you want VS Code to mount the folder of your project
      - ..:/workspace/ros_ws/src/m-explore-ros2

    # Uncomment the next four lines if you will use a ptrace-based debuggers like C++, Go, and Rust.
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined

    # Overrides default command so things don't shut down after the process ends.
    stdin_open: true
    tty: true

    command: "/bin/bash"
